//by Mohammad Bagher Abiat
public class HappyProgrammersDay {
    public static void main(String[] args) {
        System.out.println("\n\n");
        System.out.print("              MMMMMMMMM                         MMMMMMMMM\n" +
"          MMMMMMMMMMMMMMMMMM               MMMMMMMMMMMMMMMMMM\n" +
"       MMMMMMMXXXXXXXXXXMMMMMMM         MMMMMMMXXXXXXXXXXMMMMMMM\n" +
"    MMMMMMXXXXXXXXXXXXXXXXXMMMMMM     MMMMMMXXXXXXXXXXXXXXXXXMMMMMM\n" +
"   MMMMMXXXXXXXXOOOOOOOOXXXXXXMMMM   MMMMXXXXXXOOOOOOOOXXXXXXXXMMMMM\n" +
"  MMMMXXXXXXXOOOOOOOOOOOOOOOXXXXMMM MMMXXXXOOOOOOOOOOOOOOOXXXXXXXMMMM\n" +
" MMMMXXXXXXOOOOOOOOOOOOOOOOOOOOXXXMMMXXXOOOOOOOOOOOOOOOOOOOOXXXXXXMMMM\n" +
" MMMXXXXXOOOOOOOOOOOOOOOOOOOOOOOOXXXXXOOOOOOOOOOOOOOOOOOOOOOOOXXXXXMMM\n" +
"MMMXXXXXOOOOOOOOOOO       OOOOOOOOOXOOOOOOOOO       OOOOOOOOOOOOXXXXMMM\n" +
"MMMXXXXOOOOOOOOO              OOOOOOOOOOO              OOOOOOOOOOXXXMMM\n" +
"MMMXXXXOOOOOOOO                  ❤❤❤❤❤                  OOOOOOOOOXXXMMM\n" +
"MMMXXXXOOOOOOO    H A P P Y        ❤        H A P P Y    OOOOOOOOXXXMMM\n" +
"MMMXXXXOOOOOOO                                           OOOOOOOOXXXMMM\n" +
"MMMXXXXOOOOOOO             P R O G R S M M E R S         OOOOOOOOXXXMMM\n" +
"MMMXXXXXOOOOOO                                           OOOOOOOXXXXMMM\n" +
" MMMXXXXOOOOOOO                    DAY                  OOOOOOOOXXXMMM\n" +
" MMMMXXXXOOOOOOO                                       OOOOOOOOXXXMMMM\n" +
"  MMMXXXXOOOOOOOOO                                    OOOOOOOOOXXXMMM\n" +
"  MMMMXXXXOOOOOOOOOO           September 13         OOOOOOOOOOXXXMMMM\n" +
"   MMMXXXXXOOOOOOOOOOO                           OOOOOOOOOOOOXXXXMMM\n" +
"    MMMXXXXXOOOOOOOOOOOOO                     OOOOOOOOOOOOOOXXXXMMM\n" +
"     MMMXXXXXOOOOOOOOOOOOOOO               OOOOOOOOOOOOOOOOXXXXMMM\n" +
"      MMMXXXXXOOOOOOOOOOOOOOOOO         OOOOOOOOOOOOOOOOOXXXXXMMM\n" +
"       MMMXXXXXXOOOOOOOOOOOOOOOOOO   OOOOOOOOOOOOOOOOOOXXXXXXMMM\n" +
"         MMMXXXXXXXOOOOOOOOOOOOOOOO OOOOOOOOOOOOOOOOXXXXXXXMMM\n" +
"           MMMXXXXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXMMM\n" +
"             MMMMXXXXXXXXXOOOOOOOOOOOOOOOOOOOXXXXXXXXXMMMM\n" +
"                MMMMXXXXXXXXXXXOOOOOOOOOXXXXXXXXXXMMMMM\n" +
"                   MMMMMXXXXXXXXXXXOXXXXXXXXXXXMMMMM\n" +
"                      MMMMMMXXXXXXXXXXXXXXXMMMMMM\n" +
"                          MMMMMMXXXXXXXMMMMMM\n" +
"                              MMMMMXMMMMM\n" +
"                                 MMMMM\n" +
"                                  MMM\n" +
"                                   M                                    ");




    }
    
}
